### ISSUE TITLE
The registration process fails at step 8 (maven install)

### ISSUE THREAD

**Issue by menza** [ganrad/openshift-s2i-springboot-java#1]
The URL provided in the script is wrong:
`Step 8/21 : RUN (curl -fSL http://ftp.wayne.edu/apache/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz |     tar -zx -C /usr/local) &&     mv /usr/local/apache-maven-$MAVEN_VERSION /usr/local/maven &&     ln -sf /usr/local/maven/bin/mvn /usr/local/bin/mvn &&     mkdir -p $HOME/.m2 && chmod -R a+rwX $HOME/.m2
 ---> Running in caec7338e1e9
[91m[0m[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:[0m[91m-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
[0m[91m
gzip: stdin: unexpected end of file
[0m[91mtar: Child returned status 1
tar: Error is not recoverable: exiting now
[0mRemoving intermediate container caec7338e1e9
error: build error: The command '/bin/sh -c (curl -fSL http://ftp.wayne.edu/apache/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz |     tar -zx -C /usr/local) &&     mv /usr/local/apache-maven-$MAVEN_VERSION /usr/local/maven &&     ln -sf /usr/local/maven/bin/mvn /usr/local/bin/mvn &&     mkdir -p $HOME/.m2 && chmod -R a+rwX $HOME/.m2' returned a non-zero code: 2`

Please fix this, or let me help

**Comment by ganrad** [comment]
@menza please go ahead and fix it.  Create a pull request.  Thanks. Ganesh

**Comment by asebban** [comment]
@menza if you've fixed the problem, please tell me what you did. I've the same problem.

**Comment by abhinavsinha1991** [comment]
Fixed it in https://github.com/ganrad/openshift-s2i-springboot-java/pull/4.

**Comment by rofrano** [comment]
This is still not fixed in the current `README.md`. Maven version `3.6.1` does not exist at that location. You should update the docs to use Maven `3.6.3`

Example command that works:
```
docker build --build-arg MAVEN_VER=3.6.3 --build-arg GRADLE_VER=4.4 -t springboot-java .
```

**Comment by ganrad** [comment]
Thanks John.  I have updated the Readme doc.
